name: smart_home
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_gen_runner: ^5.3.1
  build_runner:
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/pictures/png/
    - assets/pictures/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
